DROP TABLE IF EXISTS BICYCLES;
DROP TABLE IF EXISTS BRAKES;
DROP TABLE IF EXISTS TRANSMISSION_COMPONENTS;
DROP TABLE IF EXISTS BRANDS;
CREATE TABLE BRANDS(ID INT NOT NULL AUTO_INCREMENT, NAME VARCHAR(30) NOT NULL, PRIMARY KEY(ID));
CREATE TABLE TRANSMISSION_COMPONENTS(ID INT NOT NULL AUTO_INCREMENT, TYPE ENUM('FD', 'RD', 'CAS', 'CRSET') NOT NULL, 
BRAND_ID INT NOT NULL REFERENCES BRAND(ID), GROUPSET VARCHAR(30) NOT NULL, SPEEDS INT NOT NULL, 
UNIQUE_CODE VARCHAR(120) NOT NULL, PRIMARY KEY(ID), UNIQUE(UNIQUE_CODE));
CREATE TABLE BRAKES(ID INT NOT NULL AUTO_INCREMENT, BRAND_ID INT NOT NULL REFERENCES BRAND(ID),
TYPE ENUM('Disc', 'Hydraulic_disc', 'V_brakes', 'Caliper', 'Drum'), PRIMARY KEY(ID));
CREATE TABLE BICYCLES(ID INT NOT NULL AUTO_INCREMENT, BRAND_ID INT NOT NULL REFERENCES BRAND(ID), 
TYPE ENUM('MTB', 'Road', 'Gravel', 'City') NOT NULL, FRAME_SIZE INT NOT NULL, WHEEL_SIZE INT NOT NULL,
HANDLEBAR_WIDTH INT NOT NULL, FRONT_DERAILLEUR INT NOT NULL REFERENCES TRANSMISSION_COMPONENTS(ID), 
REAR_DERAILLEUR INT NOT NULL REFERENCES TRANSMISSION_COMPONENTS(ID),
CASSETTE INT NOT NULL REFERENCES TRANSMISSION_COMPONENTS(ID),
CRANKSET INT NOT NULL REFERENCES TRANSMISSION_COMPONENTS(ID),BRAKES_ID INT NOT NULL REFERENCES BRAKES(ID),
SUSPENSION VARCHAR(30) NOT NULL, COLOR VARCHAR(30) NOT NULL, WEIGHT DOUBLE NOT NULL, PRICE DOUBLE NOT NULL,
ITEMS_AVAILABLE INT NOT NULL, ITEMS_SOLD INT NOT NULL, PRIMARY KEY(ID));
